apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka-service:9092']
      
      - job_name: 'trino'
        metrics_path: /metrics
        static_configs:
          - targets: ['trino-coordinator-service:8080']
      
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+) 