apiVersion: v1
kind: Service
metadata:
  name: trino-coordinator-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: trino-coordinator 