apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      containers:
        - name: trino-coordinator
          image: trinodb/trino:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/trino
              name: trino-configs
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
              cpu: "4"
      volumes:
        - name: trino-configs
          configMap:
            name: trino-configs 