apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-storage-class
provisioner: kubernetes.io/aws-ebs  # Change this based on your cloud provider
parameters:
  type: gp3  # Storage type (for AWS EBS)
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
